heat_template_version: 2014-10-16

description: >
  Extra hostname configuration

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: custom_config}
      - config: {get_resource: wipe_disk}

  custom_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        ## Set root passowrd
        sleep '10'
        echo "redhat" | passwd root --stdin
        exit 0

  wipe_disk:
    type: OS::Heat::SoftwareConfig
    properties:
      config: {get_file: wipe-disk.sh}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
